// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dfs_bc.proto

package cn.edu.ustc.center;

public final class DFSBC {
  private DFSBC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:center.Block)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .center.Block.BlockStruct struct = 1;</code>
     */
    boolean hasStruct();
    /**
     * <code>optional .center.Block.BlockStruct struct = 1;</code>
     */
    cn.edu.ustc.center.DFSBC.Block.BlockStruct getStruct();
    /**
     * <code>optional .center.Block.BlockStruct struct = 1;</code>
     */
    cn.edu.ustc.center.DFSBC.Block.BlockStructOrBuilder getStructOrBuilder();

    /**
     * <code>optional bytes signature = 2;</code>
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * Protobuf type {@code center.Block}
   */
  public  static final class Block extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:center.Block)
      BlockOrBuilder {
    // Use Block.newBuilder() to construct.
    private Block(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Block() {
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Block(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              cn.edu.ustc.center.DFSBC.Block.BlockStruct.Builder subBuilder = null;
              if (struct_ != null) {
                subBuilder = struct_.toBuilder();
              }
              struct_ = input.readMessage(cn.edu.ustc.center.DFSBC.Block.BlockStruct.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(struct_);
                struct_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              signature_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.edu.ustc.center.DFSBC.internal_static_center_Block_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.edu.ustc.center.DFSBC.internal_static_center_Block_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.edu.ustc.center.DFSBC.Block.class, cn.edu.ustc.center.DFSBC.Block.Builder.class);
    }

    public interface BlockStructOrBuilder extends
        // @@protoc_insertion_point(interface_extends:center.Block.BlockStruct)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional bytes PK = 1;</code>
       */
      com.google.protobuf.ByteString getPK();

      /**
       * <code>optional bytes parent = 2;</code>
       */
      com.google.protobuf.ByteString getParent();

      /**
       * <code>optional int32 height = 3;</code>
       */
      int getHeight();

      /**
       * <code>optional bytes payload_hash = 4;</code>
       */
      com.google.protobuf.ByteString getPayloadHash();

      /**
       * <code>optional bytes root_hash = 5;</code>
       */
      com.google.protobuf.ByteString getRootHash();

      /**
       * <code>optional bytes sym_key = 6;</code>
       */
      com.google.protobuf.ByteString getSymKey();
    }
    /**
     * Protobuf type {@code center.Block.BlockStruct}
     */
    public  static final class BlockStruct extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:center.Block.BlockStruct)
        BlockStructOrBuilder {
      // Use BlockStruct.newBuilder() to construct.
      private BlockStruct(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private BlockStruct() {
        pK_ = com.google.protobuf.ByteString.EMPTY;
        parent_ = com.google.protobuf.ByteString.EMPTY;
        height_ = 0;
        payloadHash_ = com.google.protobuf.ByteString.EMPTY;
        rootHash_ = com.google.protobuf.ByteString.EMPTY;
        symKey_ = com.google.protobuf.ByteString.EMPTY;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private BlockStruct(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {

                pK_ = input.readBytes();
                break;
              }
              case 18: {

                parent_ = input.readBytes();
                break;
              }
              case 24: {

                height_ = input.readInt32();
                break;
              }
              case 34: {

                payloadHash_ = input.readBytes();
                break;
              }
              case 42: {

                rootHash_ = input.readBytes();
                break;
              }
              case 50: {

                symKey_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.edu.ustc.center.DFSBC.internal_static_center_Block_BlockStruct_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.edu.ustc.center.DFSBC.internal_static_center_Block_BlockStruct_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.edu.ustc.center.DFSBC.Block.BlockStruct.class, cn.edu.ustc.center.DFSBC.Block.BlockStruct.Builder.class);
      }

      public static final int PK_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString pK_;
      /**
       * <code>optional bytes PK = 1;</code>
       */
      public com.google.protobuf.ByteString getPK() {
        return pK_;
      }

      public static final int PARENT_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString parent_;
      /**
       * <code>optional bytes parent = 2;</code>
       */
      public com.google.protobuf.ByteString getParent() {
        return parent_;
      }

      public static final int HEIGHT_FIELD_NUMBER = 3;
      private int height_;
      /**
       * <code>optional int32 height = 3;</code>
       */
      public int getHeight() {
        return height_;
      }

      public static final int PAYLOAD_HASH_FIELD_NUMBER = 4;
      private com.google.protobuf.ByteString payloadHash_;
      /**
       * <code>optional bytes payload_hash = 4;</code>
       */
      public com.google.protobuf.ByteString getPayloadHash() {
        return payloadHash_;
      }

      public static final int ROOT_HASH_FIELD_NUMBER = 5;
      private com.google.protobuf.ByteString rootHash_;
      /**
       * <code>optional bytes root_hash = 5;</code>
       */
      public com.google.protobuf.ByteString getRootHash() {
        return rootHash_;
      }

      public static final int SYM_KEY_FIELD_NUMBER = 6;
      private com.google.protobuf.ByteString symKey_;
      /**
       * <code>optional bytes sym_key = 6;</code>
       */
      public com.google.protobuf.ByteString getSymKey() {
        return symKey_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!pK_.isEmpty()) {
          output.writeBytes(1, pK_);
        }
        if (!parent_.isEmpty()) {
          output.writeBytes(2, parent_);
        }
        if (height_ != 0) {
          output.writeInt32(3, height_);
        }
        if (!payloadHash_.isEmpty()) {
          output.writeBytes(4, payloadHash_);
        }
        if (!rootHash_.isEmpty()) {
          output.writeBytes(5, rootHash_);
        }
        if (!symKey_.isEmpty()) {
          output.writeBytes(6, symKey_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!pK_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, pK_);
        }
        if (!parent_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, parent_);
        }
        if (height_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, height_);
        }
        if (!payloadHash_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, payloadHash_);
        }
        if (!rootHash_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(5, rootHash_);
        }
        if (!symKey_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(6, symKey_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static cn.edu.ustc.center.DFSBC.Block.BlockStruct parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.edu.ustc.center.DFSBC.Block.BlockStruct parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.edu.ustc.center.DFSBC.Block.BlockStruct parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static cn.edu.ustc.center.DFSBC.Block.BlockStruct parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static cn.edu.ustc.center.DFSBC.Block.BlockStruct parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static cn.edu.ustc.center.DFSBC.Block.BlockStruct parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static cn.edu.ustc.center.DFSBC.Block.BlockStruct parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static cn.edu.ustc.center.DFSBC.Block.BlockStruct parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static cn.edu.ustc.center.DFSBC.Block.BlockStruct parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input);
      }
      public static cn.edu.ustc.center.DFSBC.Block.BlockStruct parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(cn.edu.ustc.center.DFSBC.Block.BlockStruct prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code center.Block.BlockStruct}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:center.Block.BlockStruct)
          cn.edu.ustc.center.DFSBC.Block.BlockStructOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return cn.edu.ustc.center.DFSBC.internal_static_center_Block_BlockStruct_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return cn.edu.ustc.center.DFSBC.internal_static_center_Block_BlockStruct_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  cn.edu.ustc.center.DFSBC.Block.BlockStruct.class, cn.edu.ustc.center.DFSBC.Block.BlockStruct.Builder.class);
        }

        // Construct using cn.edu.ustc.center.DFSBC.Block.BlockStruct.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          pK_ = com.google.protobuf.ByteString.EMPTY;

          parent_ = com.google.protobuf.ByteString.EMPTY;

          height_ = 0;

          payloadHash_ = com.google.protobuf.ByteString.EMPTY;

          rootHash_ = com.google.protobuf.ByteString.EMPTY;

          symKey_ = com.google.protobuf.ByteString.EMPTY;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return cn.edu.ustc.center.DFSBC.internal_static_center_Block_BlockStruct_descriptor;
        }

        public cn.edu.ustc.center.DFSBC.Block.BlockStruct getDefaultInstanceForType() {
          return cn.edu.ustc.center.DFSBC.Block.BlockStruct.getDefaultInstance();
        }

        public cn.edu.ustc.center.DFSBC.Block.BlockStruct build() {
          cn.edu.ustc.center.DFSBC.Block.BlockStruct result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public cn.edu.ustc.center.DFSBC.Block.BlockStruct buildPartial() {
          cn.edu.ustc.center.DFSBC.Block.BlockStruct result = new cn.edu.ustc.center.DFSBC.Block.BlockStruct(this);
          result.pK_ = pK_;
          result.parent_ = parent_;
          result.height_ = height_;
          result.payloadHash_ = payloadHash_;
          result.rootHash_ = rootHash_;
          result.symKey_ = symKey_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof cn.edu.ustc.center.DFSBC.Block.BlockStruct) {
            return mergeFrom((cn.edu.ustc.center.DFSBC.Block.BlockStruct)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(cn.edu.ustc.center.DFSBC.Block.BlockStruct other) {
          if (other == cn.edu.ustc.center.DFSBC.Block.BlockStruct.getDefaultInstance()) return this;
          if (other.getPK() != com.google.protobuf.ByteString.EMPTY) {
            setPK(other.getPK());
          }
          if (other.getParent() != com.google.protobuf.ByteString.EMPTY) {
            setParent(other.getParent());
          }
          if (other.getHeight() != 0) {
            setHeight(other.getHeight());
          }
          if (other.getPayloadHash() != com.google.protobuf.ByteString.EMPTY) {
            setPayloadHash(other.getPayloadHash());
          }
          if (other.getRootHash() != com.google.protobuf.ByteString.EMPTY) {
            setRootHash(other.getRootHash());
          }
          if (other.getSymKey() != com.google.protobuf.ByteString.EMPTY) {
            setSymKey(other.getSymKey());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          cn.edu.ustc.center.DFSBC.Block.BlockStruct parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (cn.edu.ustc.center.DFSBC.Block.BlockStruct) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private com.google.protobuf.ByteString pK_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes PK = 1;</code>
         */
        public com.google.protobuf.ByteString getPK() {
          return pK_;
        }
        /**
         * <code>optional bytes PK = 1;</code>
         */
        public Builder setPK(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          pK_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes PK = 1;</code>
         */
        public Builder clearPK() {
          
          pK_ = getDefaultInstance().getPK();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString parent_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes parent = 2;</code>
         */
        public com.google.protobuf.ByteString getParent() {
          return parent_;
        }
        /**
         * <code>optional bytes parent = 2;</code>
         */
        public Builder setParent(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          parent_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes parent = 2;</code>
         */
        public Builder clearParent() {
          
          parent_ = getDefaultInstance().getParent();
          onChanged();
          return this;
        }

        private int height_ ;
        /**
         * <code>optional int32 height = 3;</code>
         */
        public int getHeight() {
          return height_;
        }
        /**
         * <code>optional int32 height = 3;</code>
         */
        public Builder setHeight(int value) {
          
          height_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 height = 3;</code>
         */
        public Builder clearHeight() {
          
          height_ = 0;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString payloadHash_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes payload_hash = 4;</code>
         */
        public com.google.protobuf.ByteString getPayloadHash() {
          return payloadHash_;
        }
        /**
         * <code>optional bytes payload_hash = 4;</code>
         */
        public Builder setPayloadHash(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          payloadHash_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes payload_hash = 4;</code>
         */
        public Builder clearPayloadHash() {
          
          payloadHash_ = getDefaultInstance().getPayloadHash();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString rootHash_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes root_hash = 5;</code>
         */
        public com.google.protobuf.ByteString getRootHash() {
          return rootHash_;
        }
        /**
         * <code>optional bytes root_hash = 5;</code>
         */
        public Builder setRootHash(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          rootHash_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes root_hash = 5;</code>
         */
        public Builder clearRootHash() {
          
          rootHash_ = getDefaultInstance().getRootHash();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString symKey_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes sym_key = 6;</code>
         */
        public com.google.protobuf.ByteString getSymKey() {
          return symKey_;
        }
        /**
         * <code>optional bytes sym_key = 6;</code>
         */
        public Builder setSymKey(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          symKey_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes sym_key = 6;</code>
         */
        public Builder clearSymKey() {
          
          symKey_ = getDefaultInstance().getSymKey();
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:center.Block.BlockStruct)
      }

      // @@protoc_insertion_point(class_scope:center.Block.BlockStruct)
      private static final cn.edu.ustc.center.DFSBC.Block.BlockStruct DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new cn.edu.ustc.center.DFSBC.Block.BlockStruct();
      }

      public static cn.edu.ustc.center.DFSBC.Block.BlockStruct getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<BlockStruct>
          PARSER = new com.google.protobuf.AbstractParser<BlockStruct>() {
        public BlockStruct parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new BlockStruct(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<BlockStruct> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<BlockStruct> getParserForType() {
        return PARSER;
      }

      public cn.edu.ustc.center.DFSBC.Block.BlockStruct getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int STRUCT_FIELD_NUMBER = 1;
    private cn.edu.ustc.center.DFSBC.Block.BlockStruct struct_;
    /**
     * <code>optional .center.Block.BlockStruct struct = 1;</code>
     */
    public boolean hasStruct() {
      return struct_ != null;
    }
    /**
     * <code>optional .center.Block.BlockStruct struct = 1;</code>
     */
    public cn.edu.ustc.center.DFSBC.Block.BlockStruct getStruct() {
      return struct_ == null ? cn.edu.ustc.center.DFSBC.Block.BlockStruct.getDefaultInstance() : struct_;
    }
    /**
     * <code>optional .center.Block.BlockStruct struct = 1;</code>
     */
    public cn.edu.ustc.center.DFSBC.Block.BlockStructOrBuilder getStructOrBuilder() {
      return getStruct();
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>optional bytes signature = 2;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (struct_ != null) {
        output.writeMessage(1, getStruct());
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(2, signature_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (struct_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getStruct());
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static cn.edu.ustc.center.DFSBC.Block parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.ustc.center.DFSBC.Block parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.ustc.center.DFSBC.Block parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.edu.ustc.center.DFSBC.Block parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.edu.ustc.center.DFSBC.Block parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.ustc.center.DFSBC.Block parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.ustc.center.DFSBC.Block parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.edu.ustc.center.DFSBC.Block parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.edu.ustc.center.DFSBC.Block parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static cn.edu.ustc.center.DFSBC.Block parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.edu.ustc.center.DFSBC.Block prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code center.Block}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:center.Block)
        cn.edu.ustc.center.DFSBC.BlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.edu.ustc.center.DFSBC.internal_static_center_Block_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.edu.ustc.center.DFSBC.internal_static_center_Block_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.edu.ustc.center.DFSBC.Block.class, cn.edu.ustc.center.DFSBC.Block.Builder.class);
      }

      // Construct using cn.edu.ustc.center.DFSBC.Block.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (structBuilder_ == null) {
          struct_ = null;
        } else {
          struct_ = null;
          structBuilder_ = null;
        }
        signature_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.edu.ustc.center.DFSBC.internal_static_center_Block_descriptor;
      }

      public cn.edu.ustc.center.DFSBC.Block getDefaultInstanceForType() {
        return cn.edu.ustc.center.DFSBC.Block.getDefaultInstance();
      }

      public cn.edu.ustc.center.DFSBC.Block build() {
        cn.edu.ustc.center.DFSBC.Block result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.edu.ustc.center.DFSBC.Block buildPartial() {
        cn.edu.ustc.center.DFSBC.Block result = new cn.edu.ustc.center.DFSBC.Block(this);
        if (structBuilder_ == null) {
          result.struct_ = struct_;
        } else {
          result.struct_ = structBuilder_.build();
        }
        result.signature_ = signature_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.edu.ustc.center.DFSBC.Block) {
          return mergeFrom((cn.edu.ustc.center.DFSBC.Block)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.edu.ustc.center.DFSBC.Block other) {
        if (other == cn.edu.ustc.center.DFSBC.Block.getDefaultInstance()) return this;
        if (other.hasStruct()) {
          mergeStruct(other.getStruct());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.edu.ustc.center.DFSBC.Block parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.edu.ustc.center.DFSBC.Block) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private cn.edu.ustc.center.DFSBC.Block.BlockStruct struct_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          cn.edu.ustc.center.DFSBC.Block.BlockStruct, cn.edu.ustc.center.DFSBC.Block.BlockStruct.Builder, cn.edu.ustc.center.DFSBC.Block.BlockStructOrBuilder> structBuilder_;
      /**
       * <code>optional .center.Block.BlockStruct struct = 1;</code>
       */
      public boolean hasStruct() {
        return structBuilder_ != null || struct_ != null;
      }
      /**
       * <code>optional .center.Block.BlockStruct struct = 1;</code>
       */
      public cn.edu.ustc.center.DFSBC.Block.BlockStruct getStruct() {
        if (structBuilder_ == null) {
          return struct_ == null ? cn.edu.ustc.center.DFSBC.Block.BlockStruct.getDefaultInstance() : struct_;
        } else {
          return structBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .center.Block.BlockStruct struct = 1;</code>
       */
      public Builder setStruct(cn.edu.ustc.center.DFSBC.Block.BlockStruct value) {
        if (structBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          struct_ = value;
          onChanged();
        } else {
          structBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .center.Block.BlockStruct struct = 1;</code>
       */
      public Builder setStruct(
          cn.edu.ustc.center.DFSBC.Block.BlockStruct.Builder builderForValue) {
        if (structBuilder_ == null) {
          struct_ = builderForValue.build();
          onChanged();
        } else {
          structBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .center.Block.BlockStruct struct = 1;</code>
       */
      public Builder mergeStruct(cn.edu.ustc.center.DFSBC.Block.BlockStruct value) {
        if (structBuilder_ == null) {
          if (struct_ != null) {
            struct_ =
              cn.edu.ustc.center.DFSBC.Block.BlockStruct.newBuilder(struct_).mergeFrom(value).buildPartial();
          } else {
            struct_ = value;
          }
          onChanged();
        } else {
          structBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .center.Block.BlockStruct struct = 1;</code>
       */
      public Builder clearStruct() {
        if (structBuilder_ == null) {
          struct_ = null;
          onChanged();
        } else {
          struct_ = null;
          structBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .center.Block.BlockStruct struct = 1;</code>
       */
      public cn.edu.ustc.center.DFSBC.Block.BlockStruct.Builder getStructBuilder() {
        
        onChanged();
        return getStructFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .center.Block.BlockStruct struct = 1;</code>
       */
      public cn.edu.ustc.center.DFSBC.Block.BlockStructOrBuilder getStructOrBuilder() {
        if (structBuilder_ != null) {
          return structBuilder_.getMessageOrBuilder();
        } else {
          return struct_ == null ?
              cn.edu.ustc.center.DFSBC.Block.BlockStruct.getDefaultInstance() : struct_;
        }
      }
      /**
       * <code>optional .center.Block.BlockStruct struct = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          cn.edu.ustc.center.DFSBC.Block.BlockStruct, cn.edu.ustc.center.DFSBC.Block.BlockStruct.Builder, cn.edu.ustc.center.DFSBC.Block.BlockStructOrBuilder> 
          getStructFieldBuilder() {
        if (structBuilder_ == null) {
          structBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              cn.edu.ustc.center.DFSBC.Block.BlockStruct, cn.edu.ustc.center.DFSBC.Block.BlockStruct.Builder, cn.edu.ustc.center.DFSBC.Block.BlockStructOrBuilder>(
                  getStruct(),
                  getParentForChildren(),
                  isClean());
          struct_ = null;
        }
        return structBuilder_;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes signature = 2;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>optional bytes signature = 2;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes signature = 2;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:center.Block)
    }

    // @@protoc_insertion_point(class_scope:center.Block)
    private static final cn.edu.ustc.center.DFSBC.Block DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.edu.ustc.center.DFSBC.Block();
    }

    public static cn.edu.ustc.center.DFSBC.Block getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Block>
        PARSER = new com.google.protobuf.AbstractParser<Block>() {
      public Block parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Block(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Block> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Block> getParserForType() {
      return PARSER;
    }

    public cn.edu.ustc.center.DFSBC.Block getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_center_Block_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_center_Block_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_center_Block_BlockStruct_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_center_Block_BlockStruct_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014dfs_bc.proto\022\006center\"\272\001\n\005Block\022)\n\006stru" +
      "ct\030\001 \001(\0132\031.center.Block.BlockStruct\022\021\n\ts" +
      "ignature\030\002 \001(\014\032s\n\013BlockStruct\022\n\n\002PK\030\001 \001(" +
      "\014\022\016\n\006parent\030\002 \001(\014\022\016\n\006height\030\003 \001(\005\022\024\n\014pay" +
      "load_hash\030\004 \001(\014\022\021\n\troot_hash\030\005 \001(\014\022\017\n\007sy" +
      "m_key\030\006 \001(\014B\033\n\022cn.edu.ustc.centerB\005DFSBC" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_center_Block_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_center_Block_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_center_Block_descriptor,
        new java.lang.String[] { "Struct", "Signature", });
    internal_static_center_Block_BlockStruct_descriptor =
      internal_static_center_Block_descriptor.getNestedTypes().get(0);
    internal_static_center_Block_BlockStruct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_center_Block_BlockStruct_descriptor,
        new java.lang.String[] { "PK", "Parent", "Height", "PayloadHash", "RootHash", "SymKey", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
